services:
  go-health-check-service:
    build: .
    ports:
      - "8080:8080"
    environment:
      - ENVIRONMENT=${ENVIRONMENT:-dev}
      - APP_VERSION=${APP_VERSION:-dev}
      - APP_NAME=go-health-check-service
      - PORT=8080
      - LOG_LEVEL=debug
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s
    restart: unless-stopped
    labels:
      - "app=go-health-check-service"
      - "environment=dev"
      - "managed-by=docker-compose"


